services:
  api:
    image: ${IMAGE:-ghcr.io/vitorhugo-java/sonicrelay-api:latest}
    container_name: sonicrelay-api
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8080"
    networks:
      - infra_network

networks:
  infra_network:
    external: true
    name: infra_network
